[build]
  command = "pip install -r requirements.txt"
  functions = "vision_backend/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.vision_backend/netlify/functions/api/:splat"
  status = 200

[functions]
  node_bundler = "esbuild" # Optional, but good for performance